on:
  push:
    branches:
      - master

jobs:
  push_to_obs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Install osc
        run: |
          sudo sh -c 'echo "deb https://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_20.04/ /" >/etc/apt/sources.list.d/osc.list'
          curl -L https://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_20.04/Release.key | sudo apt-key add -
          sudo apt update
          sudo apt-get install -y --no-install-recommends osc

      - name: Upload to OBS
        run: |
          echo -e "[https://api.opensuse.org]\nuser = ${{ secrets.OBS_USER }}\npass = ${{ secrets.OBS_PASS }}\n" >~/.oscrc
          ./bin/build-packages-for-obs && ./bin/push-packages-to-obs
        env:
          TEST: "--test"
          OSCAPI: https://api.opensuse.org
          OBS_PROJ: home:cbosdonnat:branches:systemsmanagement:Uyuni:Utils
